export const algerianStates = [
  { "value": "adrar", "code": "DZ-01", "label": { "ar": "أدرار", "fr": "Adrar" } },
  { "value": "chlef", "code": "DZ-02", "label": { "ar": "الشلف", "fr": "Chlef" } },
  { "value": "laghouat", "code": "DZ-03", "label": { "ar": "الأغواط", "fr": "Laghouat" } },
  { "value": "oum_el_bouaghi", "code": "DZ-04", "label": { "ar": "أم البواقي", "fr": "Oum El Bouaghi" } },
  { "value": "batna", "code": "DZ-05", "label": { "ar": "باتنة", "fr": "Batna" } },
  { "value": "béjaïa", "code": "DZ-06", "label": { "ar": "بجاية", "fr": "Béjaïa" } },
  { "value": "béchar", "code": "DZ-07", "label": { "ar": "بشار", "fr": "Béchar" } },
  { "value": "blida", "code": "DZ-09", "label": { "ar": "البليدة", "fr": "Blida" } },
  { "value": "bouira", "code": "DZ-10", "label": { "ar": "البويرة", "fr": "Bouira" } },
  { "value": "tamanrasset", "code": "DZ-11", "label": { "ar": "تمنراست", "fr": "Tamanrasset" } },
  { "value": "tébessa", "code": "DZ-12", "label": { "ar": "تبسة", "fr": "Tébessa" } },
  { "value": "tlemcen", "code": "DZ-13", "label": { "ar": "تلمسان", "fr": "Tlemcen" } },
  { "value": "tiaret", "code": "DZ-14", "label": { "ar": "تيارت", "fr": "Tiaret" } },
  { "value": "tizi_ouzou", "code": "DZ-15", "label": { "ar": "تيزي وزو", "fr": "Tizi Ouzou" } },
  { "value": "alger", "code": "DZ-16", "label": { "ar": "الجزائر", "fr": "Alger" } },
  { "value": "djelfa", "code": "DZ-17", "label": { "ar": "الجلفة", "fr": "Djelfa" } },
  { "value": "jiijel", "code": "DZ-18", "label": { "ar": "جيجل", "fr": "Jijel" } },
  { "value": "sétif", "code": "DZ-19", "label": { "ar": "سطيف", "fr": "Sétif" } },
  { "value": "saïda", "code": "DZ-20", "label": { "ar": "سعيدة", "fr": "Saïda" } },
  { "value": "skikda", "code": "DZ-21", "label": { "ar": "سكيكدة", "fr": "Skikda" } },
  { "value": "sidi_bel_abès", "code": "DZ-22", "label": { "ar": "سيدي بلعباس", "fr": "Sidi Bel Abbès" } },
  { "value": "annaba", "code": "DZ-23", "label": { "ar": "عنابة", "fr": "Annaba" } },
  { "value": "guelma", "code": "DZ-24", "label": { "ar": "قالمة", "fr": "Guelma" } },
  { "value": "constantine", "code": "DZ-25", "label": { "ar": "قسنطينة", "fr": "Constantine" } },
  { "value": "médéa", "code": "DZ-26", "label": { "ar": "المدية", "fr": "Médéa" } },
  { "value": "mostaganem", "code": "DZ-27", "label": { "ar": "مستغانم", "fr": "Mostaganem" } },
  { "value": "msila", "code": "DZ-28", "label": { "ar": "المسيلة", "fr": "M'Sila" } },
  { "value": "mascara", "code": "DZ-29", "label": { "ar": "معسكر", "fr": "Mascara" } },
  { "value": "ouargla", "code": "DZ-30", "label": { "ar": "ورقلة", "fr": "Ouargla" } },
  { "value": "oran", "code": "DZ-31", "label": { "ar": "وهران", "fr": "Oran" } },
  { "value": "el_bayadh", "code": "DZ-32", "label": { "ar": "البيض", "fr": "El Bayadh" } },
  { "value": "illizi", "code": "DZ-33", "label": { "ar": "إليزي", "fr": "Illizi" } },
  { "value": "bordj_bou_arreridj", "code": "DZ-34", "label": { "ar": "برج بوعريريج", "fr": "Bordj Bou Arréridj" } },
  { "value": "boumerdès", "code": "DZ-35", "label": { "ar": "بومرداس", "fr": "Boumerdès" } },
  { "value": "el_tarf", "code": "DZ-36", "label": { "ar": "الطارف", "fr": "El Tarf" } },
  { "value": "tindouf", "code": "DZ-37", "label": { "ar": "تندوف", "fr": "Tindouf" } },
  { "value": "tissemsilt", "code": "DZ-38", "label": { "ar": "تيسمسيلت", "fr": "Tissemsilt" } },
  { "value": "el_oued", "code": "DZ-39", "label": { "ar": "الوادي", "fr": "El Oued" } },
  { "value": "khenchela", "code": "DZ-40", "label": { "ar": "خنشلة", "fr": "Khenchela" } },
  { "value": "souk_ahras", "code": "DZ-41", "label": { "ar": "سوق أهراس", "fr": "Souk Ahras" } },
  { "value": "tipaza", "code": "DZ-42", "label": { "ar": "تيبازة", "fr": "Tipaza" } },
  { "value": "mila", "code": "DZ-43", "label": { "ar": "ميلة", "fr": "Mila" } },
  { "value": "ain_defla", "code": "DZ-44", "label": { "ar": "عين الدفلى", "fr": "Aïn Defla" } },
  { "value": "naama", "code": "DZ-45", "label": { "ar": "النعامة", "fr": "Naâma" } },
  { "value": "ain_témouchent", "code": "DZ-46", "label": { "ar": "عين تموشنت", "fr": "Aïn Témouchent" } },
  { "value": "ghardaïa", "code": "DZ-47", "label": { "ar": "غرداية", "fr": "Ghardaïa" } },
  { "value": "relizane", "code": "DZ-48", "label": { "ar": "غليزان", "fr": "Relizane" } },
  { "value": "timimoun", "code": "DZ-49", "label": { "ar": "تيميمون", "fr": "Timimoun" } },
  { "value": "bordj_badji_mokhtar", "code": "DZ-50", "label": { "ar": "برج باجي مختار", "fr": "Bordj Badji Mokhtar" } },
  { "value": "ouled_djellal", "code": "DZ-51", "label": { "ar": "أولاد جلال", "fr": "Ouled Djellal" } },
  { "value": "béni_abbès", "code": "DZ-52", "label": { "ar": "بني عباس", "fr": "Béni Abbès" } },
  { "value": "in_salah", "code": "DZ-53", "label": { "ar": "عين صالح", "fr": "In Salah" } },
  { "value": "in_ghar", "code": "DZ-54", "label": { "ar": "عين قزّام", "fr": "In Ghar" } },
  { "value": "touggourt", "code": "DZ-55", "label": { "ar": "تقرت", "fr": "Touggourt" } },
  { "value": "djanet", "code": "DZ-56", "label": { "ar": "جانت", "fr": "Djanet" } },
  { "value": "el_meghaier", "code": "DZ-57", "label": { "ar": "المغير", "fr": "El Meghaïer" } },
  { "value": "el_menia", "code": "DZ-58", "label": { "ar": "المنيعة", "fr": "El Menia" } }
];

// Comprehensive map of municipalities by state
export const municipalitiesByState = {
  adrar: [
    { value: "adrar-city", label: "أدرار" },
    { value: "fenoughil", label: "فنوغيل" },
    { value: "tamentit", label: "تمنطيط" },
    { value: "tamest", label: "تامست" },
    { value: "zaouiet-kounta", label: "زاوية كنتة" },
    { value: "reggane", label: "رقان" },
  ],
  chlef: [
    { value: "chlef-city", label: "الشلف" },
    { value: "tenes", label: "تنس" },
    { value: "benairia", label: "بنايرية" },
    { value: "abou-el-hassan", label: "أبو الحسن" },
    { value: "boukadir", label: "بوقادير" },
    { value: "oued-fodda", label: "وادي الفضة" },
  ],
  laghouat: [
    { value: "laghouat-city", label: "الأغواط" },
    { value: "aflou", label: "أفلو" },
    { value: "gueltat-sidi-saad", label: "قلتة سيدي سعد" },
    { value: "ain-madhi", label: "عين ماضي" },
    { value: "hassi-rmel", label: "حاسي الرمل" },
    { value: "el-assafia", label: "العسافية" },
  ],
  "oum-el-bouaghi": [
    { value: "oum-el-bouaghi-city", label: "أم البواقي" },
    { value: "ain-beida", label: "عين البيضاء" },
    { value: "ain-mlila", label: "عين مليلة" },
    { value: "sigus", label: "سيقوس" },
    { value: "ain-fakroun", label: "عين فكرون" },
    { value: "ain-kercha", label: "عين كرشة" },
  ],
  batna: [
    { value: "batna-city", label: "باتنة" },
    { value: "arris", label: "أريس" },
    { value: "barika", label: "بريكة" },
    { value: "ain-touta", label: "عين التوتة" },
    { value: "tazoult", label: "تازولت" },
    { value: "nqaous", label: "نقاوس" },
  ],
  bejaia: [
    { value: "bejaia-city", label: "بجاية" },
    { value: "akbou", label: "أقبو" },
    { value: "souk-el-tenine", label: "سوق الإثنين" },
    { value: "tichy", label: "تيشي" },
    { value: "amizour", label: "أميزور" },
    { value: "sidi-aich", label: "سيدي عيش" },
  ],
  biskra: [
    { value: "biskra-city", label: "بسكرة" },
    { value: "sidi-okba", label: "سيدي عقبة" },
    { value: "tolga", label: "طولقة" },
    { value: "ouled-djellal", label: "أولاد جلال" },
    { value: "zeribet-el-oued", label: "زريبة الوادي" },
    { value: "el-kantara", label: "القنطرة" },
  ],
  bechar: [
    { value: "bechar-city", label: "بشار" },
    { value: "abadla", label: "العبادلة" },
    { value: "kenadsa", label: "القنادسة" },
    { value: "beni-abbes", label: "بني عباس" },
    { value: "igli", label: "إقلي" },
    { value: "taghit", label: "تاغيت" },
  ],
  blida: [
    { value: "blida-city", label: "البليدة" },
    { value: "boufarik", label: "بوفاريك" },
    { value: "mouzaia", label: "موزاية" },
    { value: "el-affroun", label: "العفرون" },
    { value: "ouled-yaich", label: "أولاد يعيش" },
    { value: "meftah", label: "مفتاح" },
  ],
  bouira: [
    { value: "bouira-city", label: "البويرة" },
    { value: "lakhdaria", label: "الأخضرية" },
    { value: "sour-el-ghozlane", label: "سور الغزلان" },
    { value: "kadiria", label: "القادرية" },
    { value: "mchedallah", label: "مشدالله" },
    { value: "ain-bessem", label: "عين بسام" },
  ],
  tamanrasset: [
    { value: "tamanrasset-city", label: "تمنراست" },
    { value: "in-salah", label: "عين صالح" },
    { value: "in-guezzam", label: "عين قزام" },
    { value: "abalessa", label: "أبلسة" },
    { value: "tazrouk", label: "تازروك" },
    { value: "tin-zaouatine", label: "تين زواتين" },
  ],
  tebessa: [
    { value: "tebessa-city", label: "تبسة" },
    { value: "bir-el-ater", label: "بئر العاتر" },
    { value: "cheria", label: "الشريعة" },
    { value: "ouenza", label: "الونزة" },
    { value: "el-aouinet", label: "العوينات" },
    { value: "el-kouif", label: "الكويف" },
  ],
  tlemcen: [
    { value: "tlemcen-city", label: "تلمسان" },
    { value: "maghnia", label: "مغنية" },
    { value: "ghazaouet", label: "الغزوات" },
    { value: "nedroma", label: "ندرومة" },
    { value: "remchi", label: "الرمشي" },
    { value: "sebdou", label: "سبدو" },
  ],
  tiaret: [
    { value: "tiaret-city", label: "تيارت" },
    { value: "ksar-chellala", label: "قصر الشلالة" },
    { value: "frenda", label: "فرندة" },
    { value: "ain-kermes", label: "عين كرمس" },
    { value: "sougueur", label: "السوقر" },
    { value: "mahdia", label: "مهدية" },
  ],
  "tizi-ouzou": [
    { value: "tizi-ouzou-city", label: "تيزي وزو" },
    { value: "azazga", label: "عزازقة" },
    { value: "draa-el-mizan", label: "ذراع الميزان" },
    { value: "larbaa-nath-irathen", label: "الأربعاء ناث إيراثن" },
    { value: "ain-el-hammam", label: "عين الحمام" },
    { value: "boghni", label: "بوغني" },
  ],
  algiers: [
    { value: "algiers-centre", label: "الجزائر الوسطى" },
    { value: "bab-ezzouar", label: "باب الزوار" },
    { value: "bir-mourad-rais", label: "بئر مراد رايس" },
    { value: "el-harrach", label: "الحراش" },
    { value: "hussein-dey", label: "حسين داي" },
    { value: "bab-el-oued", label: "باب الوادي" },
    { value: "kouba", label: "القبة" },
    { value: "ain-benian", label: "عين بنيان" },
    { value: "dar-el-beida", label: "الدار البيضاء" },
    { value: "rouiba", label: "الرويبة" },
    { value: "reghaïa", label: "رغاية" },
    { value: "zeralda", label: "زرالدة" },
    { value: "draria", label: "الدرارية" },
    { value: "cheraga", label: "الشراقة" },
    { value: "bordj-el-bahri", label: "برج البحري" },
  ],
  djelfa: [
    { value: "djelfa-city", label: "الجلفة" },
    { value: "ain-oussera", label: "عين وسارة" },
    { value: "messaad", label: "مسعد" },
    { value: "hassi-bahbah", label: "حاسي بحبح" },
    { value: "dar-chioukh", label: "دار الشيوخ" },
    { value: "birine", label: "بيرين" },
  ],
  jijel: [
    { value: "jijel-city", label: "جيجل" },
    { value: "taher", label: "الطاهير" },
    { value: "el-milia", label: "الميلية" },
    { value: "sidi-abdelaziz", label: "سيدي عبد العزيز" },
    { value: "ziama-mansouriah", label: "زيامة منصورية" },
    { value: "el-ancer", label: "العنصر" },
  ],
  setif: [
    { value: "setif-city", label: "سطيف" },
    { value: "el-eulma", label: "العلمة" },
    { value: "ain-oulmene", label: "عين ولمان" },
    { value: "bougaa", label: "بوقاعة" },
    { value: "ain-arnat", label: "عين أرنات" },
    { value: "ain-kebira", label: "عين الكبيرة" },
  ],
  saida: [
    { value: "saida-city", label: "سعيدة" },
    { value: "ain-el-hadjar", label: "عين الحجر" },
    { value: "youb", label: "يوب" },
    { value: "sidi-boubekeur", label: "سيدي بوبكر" },
    { value: "ouled-brahim", label: "أولاد إبراهيم" },
    { value: "sidi-ahmed", label: "سيدي أحمد" },
  ],
  skikda: [
    { value: "skikda-city", label: "سكيكدة" },
    { value: "collo", label: "القل" },
    { value: "azzaba", label: "عزابة" },
    { value: "el-harrouch", label: "الحروش" },
    { value: "tamalous", label: "تمالوس" },
    { value: "ben-azzouz", label: "بن عزوز" },
  ],
  "sidi-bel-abbes": [
    { value: "sidi-bel-abbes-city", label: "سيدي بلعباس" },
    { value: "telagh", label: "تلاغ" },
    { value: "sfisef", label: "سفيزف" },
    { value: "mostefa-ben-brahim", label: "مصطفى بن إبراهيم" },
    { value: "marhoum", label: "مرحوم" },
    { value: "ras-el-ma", label: "رأس الماء" },
  ],
  annaba: [
    { value: "annaba-city", label: "عنابة" },
    { value: "el-bouni", label: "البوني" },
    { value: "el-hadjar", label: "الحجار" },
    { value: "berrahal", label: "برحال" },
    { value: "ain-berda", label: "عين الباردة" },
    { value: "chetaibi", label: "شطايبي" },
  ],
  guelma: [
    { value: "guelma-city", label: "قالمة" },
    { value: "oued-zenati", label: "وادي الزناتي" },
    { value: "bouchegouf", label: "بوشقوف" },
    { value: "heliopolis", label: "هيليوبوليس" },
    { value: "hammam-debagh", label: "حمام دباغ" },
    { value: "ain-makhlouf", label: "عين مخلوف" },
  ],
  constantine: [
    { value: "constantine-city", label: "قسنطينة" },
    { value: "el-khroub", label: "الخروب" },
    { value: "hamma-bouziane", label: "حامة بوزيان" },
    { value: "didouche-mourad", label: "ديدوش مراد" },
    { value: "ain-abid", label: "عين عبيد" },
    { value: "zighoud-youcef", label: "زيغود يوسف" },
    { value: "ibn-ziad", label: "ابن زياد" },
  ],
  medea: [
    { value: "medea-city", label: "المدية" },
    { value: "ksar-el-boukhari", label: "قصر البخاري" },
    { value: "ain-boucif", label: "عين بوسيف" },
    { value: "berrouaghia", label: "البرواقية" },
    { value: "tablat", label: "تابلاط" },
    { value: "chahbounia", label: "الشهبونية" },
  ],
  mostaganem: [
    { value: "mostaganem-city", label: "مستغانم" },
    { value: "ain-tedles", label: "عين تادلس" },
    { value: "hassi-mameche", label: "حاسي مماش" },
    { value: "ain-nouissy", label: "عين نويسي" },
    { value: "kheir-eddine", label: "خير الدين" },
    { value: "bouguirat", label: "بوقيراط" },
  ],
  msila: [
    { value: "msila-city", label: "المسيلة" },
    { value: "bou-saada", label: "بوسعادة" },
    { value: "sidi-aissa", label: "سيدي عيسى" },
    { value: "ain-el-melh", label: "عين الملح" },
    { value: "magra", label: "مقرة" },
    { value: "berhoum", label: "برهوم" },
  ],
  mascara: [
    { value: "mascara-city", label: "معسكر" },
    { value: "sig", label: "سيق" },
    { value: "mohammadia", label: "المحمدية" },
    { value: "tighennif", label: "تيغنيف" },
    { value: "ghriss", label: "غريس" },
    { value: "oued-el-abtal", label: "وادي الأبطال" },
  ],
  ouargla: [
    { value: "ouargla-city", label: "ورقلة" },
    { value: "hassi-messaoud", label: "حاسي مسعود" },
    { value: "touggourt", label: "تقرت" },
    { value: "el-hadjira", label: "الحجيرة" },
    { value: "ain-beida", label: "عين البيضاء" },
    { value: "sidi-khouiled", label: "سيدي خويلد" },
  ],
  oran: [
    { value: "oran-city", label: "وهران" },
    { value: "bir-el-djir", label: "بئر الجير" },
    { value: "es-senia", label: "السانية" },
    { value: "arzew", label: "أرزيو" },
    { value: "ain-turk", label: "عين الترك" },
    { value: "bethioua", label: "بطيوة" },
    { value: "gdyel", label: "قديل" },
    { value: "hassi-bounif", label: "حاسي بونيف" },
    { value: "mers-el-kebir", label: "المرسى الكبير" },
    { value: "bousfer", label: "بوسفر" },
  ],
  // Adding more municipalities for remaining states
  "el-bayadh": [
    { value: "el-bayadh-city", label: "البيض" },
    { value: "bougtob", label: "بوقطب" },
    { value: "labiodh-sidi-cheikh", label: "الأبيض سيدي الشيخ" },
    { value: "brezina", label: "بريزينة" },
    { value: "boualem", label: "بوعلام" },
  ],
  illizi: [
    { value: "illizi-city", label: "إليزي" },
    { value: "djanet", label: "جانت" },
    { value: "debdeb", label: "دبداب" },
    { value: "bordj-omar-driss", label: "برج عمر إدريس" },
    { value: "in-amenas", label: "عين أمناس" },
  ],
  "bordj-bou-arreridj": [
    { value: "bordj-bou-arreridj-city", label: "برج بوعريريج" },
    { value: "ras-el-oued", label: "رأس الوادي" },
    { value: "mansourah", label: "المنصورة" },
    { value: "medjana", label: "مجانة" },
    { value: "bordj-ghedir", label: "برج الغدير" },
  ],
  boumerdes: [
    { value: "boumerdes-city", label: "بومرداس" },
    { value: "bordj-menaiel", label: "برج منايل" },
    { value: "dellys", label: "دلس" },
    { value: "baghlia", label: "بغلية" },
    { value: "thenia", label: "الثنية" },
    { value: "khemis-el-khechna", label: "خميس الخشنة" },
  ],
  "el-tarf": [
    { value: "el-tarf-city", label: "الطارف" },
    { value: "ben-mhidi", label: "بن مهيدي" },
    { value: "bouhadjar", label: "بوحجار" },
    { value: "drean", label: "الذرعان" },
    { value: "el-kala", label: "القالة" },
  ],
  tindouf: [
    { value: "tindouf-city", label: "تندوف" },
    { value: "oum-el-assel", label: "أم العسل" },
  ],
  tissemsilt: [
    { value: "tissemsilt-city", label: "تيسمسيلت" },
    { value: "theniet-el-had", label: "ثنية الأحد" },
    { value: "bordj-bounaama", label: "برج بونعامة" },
    { value: "khemisti", label: "خميستي" },
    { value: "ammari", label: "عماري" },
  ],
  "el-oued": [
    { value: "el-oued-city", label: "الوادي" },
    { value: "djamaa", label: "جامعة" },
    { value: "debila", label: "الدبيلة" },
    { value: "hassi-khalifa", label: "حاسي خليفة" },
    { value: "robbah", label: "الرباح" },
    { value: "magrane", label: "المقرن" },
  ],
  khenchela: [
    { value: "khenchela-city", label: "خنشلة" },
    { value: "kais", label: "قايس" },
    { value: "chechar", label: "ششار" },
    { value: "bouhmama", label: "بوحمامة" },
    { value: "ain-touila", label: "عين الطويلة" },
  ],
  "souk-ahras": [
    { value: "souk-ahras-city", label: "سوق أهراس" },
    { value: "sedrata", label: "سدراتة" },
    { value: "mechroha", label: "المشروحة" },
    { value: "ouled-driss", label: "أولاد إدريس" },
    { value: "taoura", label: "تاورة" },
  ],
  tipaza: [
    { value: "tipaza-city", label: "تيبازة" },
    { value: "cherchell", label: "شرشال" },
    { value: "hadjout", label: "حجوط" },
    { value: "kolea", label: "القليعة" },
    { value: "fouka", label: "فوكة" },
    { value: "bou-ismail", label: "بو إسماعيل" },
  ],
  mila: [
    { value: "mila-city", label: "ميلة" },
    { value: "chelghoum-laid", label: "شلغوم العيد" },
    { value: "ferdjioua", label: "فرجيوة" },
    { value: "tadjenanet", label: "تاجنانت" },
    { value: "oued-athmania", label: "وادي العثمانية" },
    { value: "teleghma", label: "التلاغمة" },
  ],
  "ain-defla": [
    { value: "ain-defla-city", label: "عين الدفلى" },
    { value: "khemis-miliana", label: "خميس مليانة" },
    { value: "miliana", label: "مليانة" },
    { value: "el-attaf", label: "العطاف" },
    { value: "ain-lechiakh", label: "عين الاشياخ" },
    { value: "djendel", label: "جندل" },
  ],
  naama: [
    { value: "naama-city", label: "النعامة" },
    { value: "mecheria", label: "المشرية" },
    { value: "ain-sefra", label: "عين الصفراء" },
    { value: "asla", label: "عسلة" },
    { value: "moghrar", label: "مغرار" },
  ],
  "ain-temouchent": [
    { value: "ain-temouchent-city", label: "عين تموشنت" },
    { value: "hammam-bouhadjar", label: "حمام بوحجر" },
    { value: "beni-saf", label: "بني صاف" },
    { value: "el-malah", label: "المالح" },
    { value: "ain-larbaa", label: "عين الأربعاء" },
  ],
  ghardaia: [
    { value: "ghardaia-city", label: "غرداية" },
    { value: "metlili", label: "متليلي" },
    { value: "berriane", label: "بريان" },
    { value: "el-guerrara", label: "القرارة" },
    { value: "zelfana", label: "زلفانة" },
    { value: "el-meniaa", label: "المنيعة" },
  ],
  relizane: [
    { value: "relizane-city", label: "غليزان" },
    { value: "oued-rhiou", label: "وادي رهيو" },
    { value: "ammi-moussa", label: "عمي موسى" },
    { value: "zemmoura", label: "زمورة" },
    { value: "djidiouia", label: "جديوية" },
    { value: "el-matmar", label: "المطمر" },
  ],
  timimoun: [
    { value: "timimoun-city", label: "تيميمون" },
    { value: "ougrout", label: "أوقروت" },
    { value: "tinerkouk", label: "تينركوك" },
    { value: "aougrout", label: "أوقروت" },
  ],
  "bordj-badji-mokhtar": [
    { value: "bordj-badji-mokhtar-city", label: "برج باجي مختار" },
    { value: "timiaouine", label: "تيمياوين" },
  ],
  "ouled-djellal": [
    { value: "ouled-djellal-city", label: "أولاد جلال" },
    { value: "sidi-khaled", label: "سيدي خالد" },
    { value: "doucen", label: "الدوسن" },
    { value: "chaiba", label: "الشعيبة" },
  ],
  "beni-abbes": [
    { value: "beni-abbes-city", label: "بني عباس" },
    { value: "kerzaz", label: "كرزاز" },
    { value: "ouled-khodeir", label: "أولاد خضير" },
    { value: "tamtert", label: "تامترت" },
  ],
  "in-salah": [
    { value: "in-salah-city", label: "عين صالح" },
    { value: "foggaret-ezzaouia", label: "فقارة الزوى" },
    { value: "in-ghar", label: "إينغر" },
  ],
  "in-guezzam": [
    { value: "in-guezzam-city", label: "عين قزام" },
    { value: "tin-zaouatine", label: "تين زواتين" },
  ],
  touggourt: [
    { value: "touggourt-city", label: "تقرت" },
    { value: "tebesbest", label: "تبسبست" },
    { value: "nezla", label: "النزلة" },
    { value: "temacine", label: "تماسين" },
    { value: "megarine", label: "المقارين" },
  ],
  djanet: [
    { value: "djanet-city", label: "جانت" },
    { value: "bordj-el-haouas", label: "برج الحواس" },
  ],
  "el-mghair": [
    { value: "el-mghair-city", label: "المغير" },
    { value: "still", label: "سطيل" },
    { value: "sidi-khelil", label: "سيدي خليل" },
    { value: "oum-touyour", label: "أم الطيور" },
  ],
  "el-meniaa": [
    { value: "el-meniaa-city", label: "المنيعة" },
    { value: "hassi-gara", label: "حاسي القارة" },
    { value: "hassi-fehal", label: "حاسي الفحل" },
  ],
}