// Generated by Wrangler on Sun Jun 30 2024 14:21:50 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
  DB: D1Database;
}

interface ImportMetaEnv {
  readonly DB_ID: string;
  readonly CLOUDFLARE_ACCOUNT_EMAIL?: string;
  readonly CLOUDFLARE_ACCOUNT_ID?: string;
  readonly D1_TOKEN?: string;
  readonly LOCAL_DB_PATH?: string;
  readonly CLOUDFLARE_API_KEY: string;
  readonly SECRET_API_TOKEN?: string;
  readonly WORKER_API_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
